POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "abula martins",
    "email": "abulamartins@gmail.com",
    "password": "test123"
}

###


POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "abulachizor@gmail.com",
    "password": "test123"
}